import { Lilita_One, Concert_One, Work_Sans } from "next/font/google";

import "./globals.css";
import NavBar from "@/components/sections/navbar/NavBar";
import LenisProvider from "@/components/providers/LenisProvider";

const lilita = Lilita_One({
  subsets: ["latin"],
  weight: "400", // Lilita One solo tiene 400
  variable: "--font-lilita",
});

const concert = Concert_One({
  subsets: ["latin"],
  weight: "400", // Concert One solo tiene 400
  variable: "--font-concert",
});

const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // pesos que quieras usar
  variable: "--font-work",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lilita.variable} ${concert.variable} ${workSans.variable} antialiased`}
      >
        <LenisProvider>
          <NavBar />
          {children}
        </LenisProvider>
      </body>
    </html>
  );
}
